# 连接池配置:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false
    username: root
    password: zhouhan2003


# mybatis-plus配置:
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.pojo
